version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: crud_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongo-data:/data/db

  backend:
    image: mallikarjuningali/crud-dd-backend:latest
    container_name: crud_backend
    depends_on:
      - mongo
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongoadmin:examplepassword@mongo:27017/cruddb?authSource=admin
    restart: unless-stopped

  nginx:
    image: mallikarjuningali/crud-dd-frontend:latest   # THIS SERVES ANGULAR + API PROXY
    container_name: crud_nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  mongo-data:

